services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.

   ##################################################################################################
   ########################################## ФАБРИКИ ###############################################
   ##################################################################################################

   # Фабрика для создания объектов БИК.
   Maris\Symfony\DocumentUnit\Factory\BikFactory: ~

   # Фабрика для создания объектов ИНН.
   Maris\Symfony\DocumentUnit\Factory\InnFactory: ~

   # Фабрика для создания объектов КПП.
   Maris\Symfony\DocumentUnit\Factory\KppFactory: ~

   # Фабрика для создания объектов ОГРНИП / ОГРНЮЛ.
   Maris\Symfony\DocumentUnit\Factory\OgrnFactory: ~